// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSjd6TnmiGpqBBFk_lRhclerhFC5Y-6pU',
    appId: '1:528993858070:web:41f958ad5f059081f97b37',
    messagingSenderId: '528993858070',
    projectId: 'pomodoro-cloud-sync',
    authDomain: 'pomodoro-cloud-sync.firebaseapp.com',
    storageBucket: 'pomodoro-cloud-sync.firebasestorage.app',
    measurementId: 'G-CPS7K4CVXW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGu6rEWEm686pPt8pcEiMmG8EQ9m731rQ',
    appId: '1:528993858070:android:00fce007d1f3de6ef97b37',
    messagingSenderId: '528993858070',
    projectId: 'pomodoro-cloud-sync',
    storageBucket: 'pomodoro-cloud-sync.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbW9PYGI-zVMhpz6m34riWWdkR3j9rp24',
    appId: '1:528993858070:ios:60c51732c846c071f97b37',
    messagingSenderId: '528993858070',
    projectId: 'pomodoro-cloud-sync',
    storageBucket: 'pomodoro-cloud-sync.firebasestorage.app',
    androidClientId: '528993858070-cr2rtare2h6e2t4ms1cj0lot1etfc827.apps.googleusercontent.com',
    iosClientId: '528993858070-32tue17b1da3mfnri6lkg5vgiuqte2ag.apps.googleusercontent.com',
    iosBundleId: 'com.antigravity.pomodoroTimer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbW9PYGI-zVMhpz6m34riWWdkR3j9rp24',
    appId: '1:528993858070:ios:60c51732c846c071f97b37',
    messagingSenderId: '528993858070',
    projectId: 'pomodoro-cloud-sync',
    storageBucket: 'pomodoro-cloud-sync.firebasestorage.app',
    androidClientId: '528993858070-cr2rtare2h6e2t4ms1cj0lot1etfc827.apps.googleusercontent.com',
    iosClientId: '528993858070-32tue17b1da3mfnri6lkg5vgiuqte2ag.apps.googleusercontent.com',
    iosBundleId: 'com.antigravity.pomodoroTimer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSjd6TnmiGpqBBFk_lRhclerhFC5Y-6pU',
    appId: '1:528993858070:web:75aab9fba34743bcf97b37',
    messagingSenderId: '528993858070',
    projectId: 'pomodoro-cloud-sync',
    authDomain: 'pomodoro-cloud-sync.firebaseapp.com',
    storageBucket: 'pomodoro-cloud-sync.firebasestorage.app',
    measurementId: 'G-CFT3TJVG46',
  );
}
